fix(tsp): use %u to display unsigned values
When enabling -Wformat-signedness option, several warnings occur when
compiling TSP.
For example:
bl32/tsp/tsp_main.c: In function 'tsp_main':
include/common/debug.h:47:41: error: format '%d' expects argument of
 type 'int', but argument 3 has type 'uint32_t' {aka 'unsigned int'}
 [-Werror=format=]
   47 | #define LOG_MARKER_INFO                 "\x28"  /* 40 */
      |                                         ^~~~~~
include/common/debug.h:83:32: note: in expansion of macro
 'LOG_MARKER_INFO'
   83 | # define INFO(...)      tf_log(LOG_MARKER_INFO __VA_ARGS__)
      |                                ^~~~~~~~~~~~~~~
bl32/tsp/tsp_main.c:48:9: note: in expansion of macro 'INFO'
   48 |         INFO("TSP: cpu 0x%lx: %d smcs, %d erets %d cpu on
 requests\n",
      |         ^~~~

Use %u instead of %d to correct that (or PRIu64 instead of PRId64).

Change-Id: I50b4626d2090350c647bc9fd11a4d1bc174a4ee0
Signed-off-by: Yann Gautier <yann.gautier@st.com>