fix(a8k): declare amb_memory_map as an array
The DDR files used in CI were recently updated. They introduce a
requriement for GCC 14 and new flags into CFLAGS, including
`-Wsizeof-pointer-div`. This results in the following compiler warning
when building for this platform:

```
plat/marvell/armada/a8k/a70x0_amc/board/marvell_plat_config.c: In
function 'marvell_get_amb_memory_map': include/lib/utils_def.h:15:20:
error: division 'sizeof (struct addr_map_win *) / sizeof (struct
addr_map_win)' does not compute the number of array elements
[-Werror=sizeof-pointer-div] 15 | (sizeof(a) / sizeof((a)[0])) | ^
plat/marvell/armada/a8k/a70x0_amc/board/marvell_plat_config.c:30:25:
note: in expansion of macro 'ARRAY_SIZE'
```

The warning occurs because ARRAY_SIZE() was used on a pointer
(amb_memory_map) instead of an actual array. In that case the expression
becomes sizeof(pointer) / sizeof(element), which does not represent the
number of elements and therefore triggers the compiler warning
-Wsizeof-pointer-div (treated as an error due to -Werror). Fix the
declaration of amb_memory_map to pacify the compiler.

Change-Id: I5608be6401bfbc1291ded85a8fbce8abe169dbe2
Signed-off-by: Harrison Mutai <harrison.mutai@arm.com>
(cherry picked from commit 5cffee40ff472f197ddf3e93d7fc579d87fc8911)