fix(mediatek): fix mtcmos build failure
Fix mtcmos build failure due to lack of definition:
plat/mediatek/drivers/mtcmos/mtcmos_common.h:16:9:
error: unknown type name 'uint32_t'
plat/mediatek/drivers/mtcmos/mt8189/mtcmos.h:31:41:
error: implicit declaration of function 'BIT'

Signed-off-by: irving-ch-lin <irving-ch.lin@mediatek.com>
Change-Id: I6550f2b99d43c72471d481eff081affe098144dd