feat(lib): introduce check_size_t_overflow
Create a check_size_t_overflow that will default to either:
- check_u64_overflow for __aarch64__ platforms
- check_u32_overflow otherwise (aarch32 platforms)

On aarch32 platform, and when enabling -Wsign-compare flag, there is a
warning:
drivers/io/io_block.c: In function 'block_open':
include/lib/utils_def.h:215:17: error: comparison of promoted bitwise
 complement of an unsigned value with unsigned [-Werror=sign-compare]
  215 |         ((_u64) > (UINT64_MAX - (_inc)))
      |                 ^
drivers/io/io_block.c:146:13: note: in expansion of macro
 'check_u64_overflow'
  146 |         if (check_u64_overflow((uint64_t)region->offset,
      |             ^~~~~~~~~~~~~~~~~~

Adding this helper corrects that.

Change-Id: Ie0cde2e8478fcb2a6e8f88cf8bfa4e6ac00b080d
Signed-off-by: Yann Gautier <yann.gautier@st.com>
(cherry picked from commit 1d5817e7840b45d0070534da230e0f8461a648d8)