fix(bl1): use #ifdef for some BL1U/BL2U flags
Those flags are defined in C header files, so they are either defined
or do not exist. This triggers a build error with -Wundef:
14:38:07 bl1/tbbr/tbbr_img_desc.c:30:5: error: 'SCP_BL2U_BASE' is not
 defined, evaluates to '0' [-Werror=undef]
14:38:07    30 | #if SCP_BL2U_BASE
14:38:07       |     ^~~~~~~~~~~~~
14:38:07 bl1/tbbr/tbbr_img_desc.c:41:5: error: 'BL2U_BASE' is not
 defined, evaluates to '0' [-Werror=undef]
14:38:07    41 | #if BL2U_BASE
14:38:07       |     ^~~~~~~~~
14:38:07 bl1/tbbr/tbbr_img_desc.c:53:5: error: 'NS_BL2U_BASE' is not
 defined, evaluates to '0' [-Werror=undef]
14:38:07    53 | #if NS_BL2U_BASE
14:38:07       |     ^~~~~~~~~~~~

Only the #ifdef should have been sufficient, bu it was changing the
behavior, as a value defined to 0 would have added the entry to the
table. So we check both the existence of a flag and that is is non null.

Change-Id: I8967eb71e438c56b2d4c1789a1b89d2f488b37ab
Signed-off-by: Yann Gautier <yann.gautier@st.com>